const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Behaviors.jumpthru,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Якорь: 0},
	{Спрайт: 0},
	{Gemini_Generated_Image_euj1m6euj1m6euj: 0},
	{Твёрдый: 0},
	{ТайловыйФон: 0},
	{СледитьЗа: 0},
	{Платформер: 0},
	{Спрайт2: 0},
	{Тач: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{ТайловыйФон2: 0},
	{Мигание: 0},
	{Спрайт6: 0},
	{Текст: 0},
	{Спрайт7: 0},
	{ВводТекста: 0},
	{Текст2: 0},
	{СквознаяПлатформа: 0},
	{ТайловыйФон3: 0},
	{блок: 0},
	{Аудио: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Счет: 0},
	{Всего: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Gemini_Generated_Image_euj1m6euj1m6euj: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Текст2: class extends self.ITextInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	блок: class extends self.ITiledBackgroundInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {}
}